services:
  php:
    container_name: kitchen-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./api:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
      # - redis
      - rabbitmq
      - phpmyadmin
    networks:
      - kitchen-network

  nginx:
    container_name: kitchen-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - "8802:80"
    volumes:
      - ./api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kitchen-network

  mysql:
    container_name: kitchen-mysql
    image: mysql:8.0
    restart: always
    tty: true
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - kitchen-network
    ports:
      - "3304:3306"
    environment:
      MYSQL_DATABASE: kitchen_ao
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_USER: kitchen
      MYSQL_PASSWORD: secret

  phpmyadmin:
    container_name: kitchen-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - "8891:80"
    networks:
      - kitchen-network
    environment:
      PMA_HOST: kitchen-mysql
    depends_on:
      - mysql
  rabbitmq:
    container_name: kitchen-rabbitmq
    image: rabbitmq:3-management
    build:
      context: ./docker/rabbitmq
      dockerfile: Dockerfile
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: always
    ports:
      - 5674:5672
      - 5675:5672
    networks:
      - kitchen-network
  # redis:
  #   container_name: kitchen-redis
  #   build:
  #     context: ./docker/redis
  #     dockerfile: Dockerfile
  #   ports:
  #     - "6380:6379"

networks:
  kitchen-network:
    driver: bridge

volumes:
  setup-data:
    driver: local
